### ISSUE TITLE
🌟 [EPIC] Gestaltung des Yunite Netzwerks und gewünsche Anpassungen von Ocelot.Social

### ISSUE THREAD

**Issue by Tirokk** [Yunite-Net/Yunite-Net-Ocelot-Social-Deploy-Rebranding#4]
### Gestaltung des Yunite Netzwerks und gewünsche Anpassungen von Ocelot.Social.

- [x] Gruppen ( @Tirokk @Mogge @ogerly )
  - https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5059
- [x] Kategorien: ( @Mogge )
  - [x] HC Kategorien wieder implementieren: https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5102
  - [x] zu Yunite Kategirien umbauen
  - [x] filtern
  - [x] speichern
- [x] Suche (@Mogge)
  - [x] Legende in die Suche https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5079
  - [x] Gruppen in die Suche
    - [x] in die Suchlegende
    - [x] in das Ergebnismenü
    - [x] in die Ergebnisse-Seite
- [x] Design ( @UlfTramsen @ogerly )
  - [x] Logo:
    - [x] Wird von @UlfTramsen geliefert: siehe → [Informationen:Logos](#user-content-logos)
    - [x] Einbau von @ogerly 
  - [x] Styleguide:
    - [x] Wird von @UlfTramsen geliefert: siehe → [Informationen:Styleguide](#user-content-styleguide)
    - [x] Einbau von @ogerly 
  - [x] Icons:
    - Im Code gibt es schon diese:
      - https://styleguide.human-connection.org/typography/dsicon
    - Aufgaben:
      - [x] Kategorien:
        - [x] Fehlende Icons für die Kategorien erstellt @UlfTramsen . Unter Berücksichtigung der existierenden und des einheitlichen Designs.
    - Info zu Kategorien: siehe → [Informationen:Kategorien](#user-content-kategorien)
  - [x] Kopfleisten-Menüs:
    - Siehe https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5153
    - [x] `Beiträge`
      - [x] Führt zum News-Feed
    - [x] `Gruppen`
      - [x] Führt zur `Meine Gruppen`
    - [x] `Über Yunite`
      - [x] Was soll in den Unternemüs stehen?
    - [x] Übersetzungsmöglichkeit, siehe `DevOps`.
  - [x] Fußzeile:
    - [x] im hellen Grün als Hintergrund
    - [x] Schrift in grau, siehe auch yunite.org
    - [x] Übersetzungsmöglichkeit, siehe `DevOps`.
  - [x] Code-Interne Seiten:
    - [x] Werden größtenteils unter `yunite.org` in Wordpress umgesetzt.
    - [x] Es soll keine Code-Internen Seiten geben
  - [x] Mobile (@ogerly )
    - [x] Fußzeile teilweise in das Hamburger-Menü
      - [x] Siehe: https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/4732
      - [ ] Rechtlich relevante Links sollen sichtbar bleiben: ( @UlfTramsen fragen und nach platzsparender Lösung suchen)
        - [x] Datenschutzerklärung
        - [x] Impressum
- [x] DevOps
  - [x] Im Rebranding Repository sollten wir die Möglichkeit haben die Einträge in den Sprach-JSON-Datien zu ersetzen oder hinzuzufügen. (siehe issue https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/issues/73 ) ( @Mogge )
    - [x] Dann können wir das Kopfzeilenmenü und den Seitenfuß übersetzen.
  - [x] DockerHub Image Repository erstellen. ( @Tirokk )
    - [x] Läuft im Moment über meinen Account
- [x] Server mit Managed Kubernetes ( @LarsE11 @UlfTramsen )
  - [x] Vorab auf DigitalOcean hosten? ( @LarsE11 fragen )
    - [x] erst mal einen Staging-Test-Server
      - [ ] E-Mails noch richtig einrichten
    - [x] und dann auch wohl zu Beginn die Produktionsumgebung
  - [ ] Unser Freund David hat für das Kubernetes Hosting noch auf folgenden Anbieter aufmerksam gemacht:
    - https://datacenterlight.ch/
- [x] Domains registrieren ( @LarsE11 @UlfTramsen )
  - [x] `yunite.me`
  - [x] `stage.yunite.me`
  - [x] `yunite.org`
    - [https://yunite.org](https://yunite.org)
      - Login:
        - User: `tm`
        - Passwort: `tm`
- [x] E-Mails ermöglichen ( @LarsE11 @UlfTramsen )
  - [x] `support@yunite.me`
  - [x] `hello@yunite.me`
  - [x] `server-stage@yunite.org`

#### Kategorien  <a href="#user-content-kategorien" id="kategorien">#</a>

```
users                Vernetzung: Kooperation, Aktionsbündnisse, Solidarität, Hilfe
home                 Wohnen: Bauen, Lebensgemeinschaften, Tiny Houses, Gemüsegarten
lightbulb            Energie: Öl, Gas, Kohle, Wind, Wasserkraft, Biogas, Atomenergie, ...
smile                Psyche: Seele, Gefühle, Glück
bewegung*            Körper & Bewegung: Sport, Yoga, Massage, Tanzen, Entspannung
balance-scale        Recht: Menschenrechte, Gesetze, Verordnungen
money                Finanzen: Geld, Finanzsystem, Alternativwährungen, ...
child                Kinder: Familie, Pädagogik, Schule, Prägung
suitcase             Mobilität: Reise, Verkehr, Elektromobilität
shopping-cart        Wirtschaft: Handel, Konsum, Marketing, Lebensmittel, Lieferketten, ...
angellist            Frieden: Krieg, Militär, soziale Verteidigung, Waffen, Cyberattacken
university               Politik: Demokratie, Mitbestimmung, Wahlen, Korruption, Parteien
tree                         Natur: Tiere, Pflanzen, Landwirtschaft, Ökologie, Artenvielfalt
graduation-cap     Wissenschaft: Bildung, Hochschule, Publikationen, ...
medkit                   Gesundheit: Medizin, Ernährung, WHO, Impfungen, Schadstoffe, ...
desktop                 IT & Medien: Nachrichten, Manipulation, Datenschutz, Überwachung, Datenkraken, AI, Software, Apps
heart-o                  Spiritualität: Religion, Werte, Ethik
music                    Kultur: Kunst, Theater, Musik, Fotografie, Film
ellipsis-h               Sonstiges
```

*: Hat @UlfTramsen im Discord über @LarsE11 zu uns gesendet:

![bewegung-ui-icon_01](https://user-images.githubusercontent.com/25344101/185053114-f959dd02-e444-4d20-8bdc-d4bec36184da.svg)

#### Logos  <a href="#user-content-logos" id="logos">#</a>

*: Hat @UlfTramsen im Discord über @LarsE11 zu uns gesendet:

![yunite-logo_01](https://user-images.githubusercontent.com/25344101/185055175-9f42930b-0a31-4a80-a17f-58b5bcae1a99.svg)
![yunite-social-icon_01](https://user-images.githubusercontent.com/25344101/185055178-37c03ebc-1ce3-4cf0-bcfc-bfeab870902a.svg)

#### Styleguide  <a href="#user-content-styleguide" id="styleguide">#</a>

*: Hat @UlfTramsen im Discord über @LarsE11 zu uns gesendet:

[yunite_styleguide_01.pdf](https://github.com/Yunite-Net/Yunite-Net-Ocelot-Social-Deploy-Rebranding/files/9357206/yunite_styleguide_01.pdf)

### Diskussion

- Kategorien:
  - Ggf. offensichtlich die ausgewählten Filter (an der Seite?) anzeigen, damit die Nutzer sehen, was sie sehen.
- Sicherheit:
  - Gespräch mit Mark.
  - Siehe E-Mail an Mark.
  - Anschließend aufgetauchte Fragen:
    - Wie sicher ist ein Letsencrypt Zertifikat?

**Comment by ulfgebhardt** [comment]
done
